### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by saltyseadoggo** [Eilux/BetterSlabs#10]
I'm afraid I haven't much else to say, just this crash report to provide.
[crash-2020-11-18_22.02.55-client.txt](https://github.com/Eilux/BetterSlabs/files/5564726/crash-2020-11-18_22.02.55-client.txt)

**Comment by saltyseadoggo** [comment]
The crash fixed by the most recent update was not this one.

**Comment by Eilux** [comment]
hmm are you sure that it isn't a different crash this time?

**Comment by saltyseadoggo** [comment]
This is the new crash report generated by adding BetterSlabs to the same mod lineup as the previous. They appear to be identical, with the exception of one number in a few places.
[crash-2020-11-19_18.02.03-client.txt](https://github.com/Eilux/BetterSlabs/files/5570840/crash-2020-11-19_18.02.03-client.txt)

**Comment by mgrabov** [comment]
I have the same stacktrace, however I only started getting after upgrading to the latest Fabric loader. I don't remember which version I was on before for which it loaded fine:

`java.lang.NullPointerException: Initializing game
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient.lambda$createPack$2(BetterslabsClient.java:55)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient$$Lambda$6389/1047399172.accept(Unknown Source)
	at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.<init>(ArtificeResourcePackImpl.java:80)
	at com.swordglowsblue.artifice.api.ArtificeResourcePack.ofAssets(ArtificeResourcePack.java:128)
	at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:50)
	at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:29)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient.createPack(BetterslabsClient.java:36)
	at net.minecraft.class_310.handler$zph000$MinecraftClient(class_310.java:5866)
	at net.minecraft.class_310.<init>(class_310.java:592)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)`

**Comment by Eilux** [comment]
see if the new release fixes this

**Comment by saltyseadoggo** [comment]
It seems to be fixed, but I haven't tested with the exact same mod lineup as before.
